server:port: 8080

name: 张培溶

absoluteImgPath: D://homework/schoolMarket_master/schoolMarket_uniapp/static/store/
sonImgPath: ../../static/store/


spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/schoolmarket?setUnicode=true&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: zhang

spring.servlet.multipart.max-file-size: 10MB
spring.servlet.multipart.max-request-size: 100MB

